fix: add dependency to avoid `NoClassDefFoundError`
```log
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
```